# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-social-cards-2',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/test-social-cards-2',
                'lib_path': 'test_social_cards_2'},
  'syms': {'test_social_cards_2.core': {'test_social_cards_2.core.foo': ('core.html#foo', 'test_social_cards_2/core.py')}}}
